# Copyright 2025 InfluxData
# Author: Carlos A. Perez Garcia (cpgarcia518@gmail.com)

services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - ${INFLUXDB_HTTP_PORT}:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - LOG_FILTER=debug
    volumes:
      - /mnt/data/influxdb2/data:/var/lib/influxdb2
      - /mnt/data/influxdb2/config:/etc/influxdb2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - net_interface


  telegraf:
    container_name: telegraf
    build:
      context: ./services/telegraf
      dockerfile: Dockerfile
    depends_on:
      influxdb2:
        condition: service_healthy
    environment:
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_HTTP_PORT}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET_2}
      - INFLUXDB_CLOUD_URL=${INFLUXDB_CLOUD_URL}
      - INFLUXDB_CLOUD_ORG=${INFLUXDB_CLOUD_ORG}
      - INFLUXDB_CLOUD_TOKEN=${INFLUXDB_CLOUD_TOKEN}
      - TELEGRAF_COLLECTION_INTERVAL=${TELEGRAF_COLLECTION_INTERVAL}
      - HOSTNAME=telegraf
      - HOBO_API_TOKEN=${HOBO_API_TOKEN}
      - HOBO_API_URL=${HOBO_API_URL}
      - HOBO_API_VERSION=${HOBO_API_VERSION}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      # - START_DATE_TIME=${START_DATE_TIME}       # Optional
      # - END_DATE_TIME=${END_DATE_TIME}           # Optional
    restart: unless-stopped
    networks:
      - net_interface

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Rome
      - NODE_RED_CREDENTIAL_SECRET=admin
    ports:
      - "1880:1880"
    networks:
      - net_interface
    volumes:
      - /mnt/data/node_red/data:/data

  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_LOG_LEVEL=debug
      # - GF_PLUGINS_PREINSTALL=grafana-simple-json-datasource
      # - GF_AWS_default_ACCESS_KEY_ID__FILE=/run/secrets/aws_access_key_id
      - GF_FEATURE_TOGGLES_PROVISIONING=true
      # - GF_FEATURE_TOGGLES_KUBERNETESCLIENTDASHBOARDSFOLDERS=true
      # - GF_FEATURE_TOGGLES_KUBERNETESDASHBOARDS=k8s
      # - GF_FEATURE_TOGGLES_GRAFANAAPISERVERENSUREKUBECTLACCESS=true   # If you want easy kubectl setup development mode
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - net_interface
    volumes:
      - /mnt/data/grafana/storage:/var/lib/grafana
      

networks:
  net_interface:
    external: true
