# Copyright 2025 InfluxData
# Author: Carlos A. Perez Garcia (cpgarcia518@gmail.com)

services:
  # influxdb2:
  #   container_name: influxdb2
  #   image: influxdb:2
  #   ports:
  #     - "${INFLUXDB_HTTP_PORT}:8086"
  #   volumes:
  #     - influxdb2-data:/var/lib/influxdb2
  #     - influxdb2-config:/etc/influxdb2
  #   environment:
  #     # - INFLUXDB3_AUTH_TOKEN=${INFLUXDB_TOKEN}
  #     # - INFLUXDB_ORG=${INFLUXDB_ORG}
  #     - LOG_FILTER=debug
  #     - INFLUXDB_INIT_MODE=setup
  #     - INFLUXDB_ADMIN_USERNAME=${INFLUXDB_ADMIN_USER}
  #     - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
  #     - INFLUXDB_ORG_NAME=${INFLUXDB_ORG}
  #     - INFLUXDB_BUCKET_NAME=${INFLUXDB_BUCKET}


  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      # - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      # - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin67890
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      # - DOCKER_INFLUXDB_INIT_ORG=admin
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      # - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    ports:
      - 8086:8086
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
      # - ./influxdb/data:/var/lib/influxdb2
      # - ./influxdb/config:/etc/influxdb2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  influxdb2-data: {}
  influxdb2-config: {}
    
networks:
  net_interface:
    external: true