services:
  container_name: influxdb2
  image: influxdb:2
  ports:
    - "${INFLUXDB_HTTP_PORT}:8086"
  volumes:
    - influxdb2-data:/var/lib/influxdb2
    - influxdb2-config:/etc/influxdb2
  environment:
    - INFLUXDB_INIT_MODE=setup
    - INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
    - INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
    - INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
    - INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
    interval: 30s
    timeout: 10s
    retries: 3
  restart: unless-stopped


  # Token 5StoLkuBVZzW-UMAK5K2Kt_MvTS-7_Atus9MpnxgldAkwyiQV3_hlr8EmsFapRN56-3bsNSznXVblCUW_BeDyw==