name: Deploy InfluxDB Stack

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'services/influxdb/**'
      - 'docker-compose.yml'
      - '.env'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    #   - name: Load environment variables
    #     run: |
    #       cp env.example .env
    #       echo "INFLUXDB_VERSION=2.7" >> .env

    #   - name: Install Docker Compose
    #     run: |
    #       sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #       sudo chmod +x /usr/local/bin/docker-compose

    #   - name: Deploy InfluxDB
    #     run: |
    #       docker-compose -f docker-compose.yml up -d influxdb
    #       sleep 10  # Wait for initialization
    #       docker ps